matrix:
  include:
  - language: android
    jdk: oraclejdk8
    before_install:
    - nvm install 10.18.1
    - echo yes | sdkmanager "platforms;android-28"
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
    - export PATH=$HOME/.yarn/bin:$PATH
    android:
      components:
      - tools
      - platform-tools
      - build-tools-28.0.3
      - tools
    cache:
      bundler: true
      yarn: true
      directories:
      - example/node_modules
      - "$HOME/.gradle/caches/"
      - "$HOME/.gradle/wrapper/"
    before_cache:
    - rm -f example/node_modules/\@react-native-mapbox-gl/
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - os: osx
    osx_image: xcode11.3
    node_js: 10.18.1
    cache:
      bundler: true
      yarn: true
      cocoapods: true
      directories:
      - example/node_modules
      - "$HOME/Library/Caches/Homebrew"
    before_cache:
    - rm -f example/node_modules/\@react-native-mapbox-gl/
    - brew cleanup
    podfile: example/ios/Podfile
before_install:
- nvm use 10.18.1 
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
- export PATH=$HOME/.yarn/bin:$PATH
install:
- cd $TRAVIS_BUILD_DIR/example
- echo $MAPBOX_ACCESS_TOKEN > ./accesstoken
- find node_modules -name ".git" -exec rm -r "{}" \; || true
- rm -rf example/node_modules/\@react-native-mapbox-gl/
- yarn install --ignore-engines
- echo $TRAVIS_OS_NAME
- |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    cd $TRAVIS_BUILD_DIR/example/ios
    pod install
    pod update
    gem install xcpretty
  fi
script:
- |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    cd $TRAVIS_BUILD_DIR/example/ios
    set -o pipefail
    rm -f build
    xcodebuild -arch x86_64 -sdk iphonesimulator13.2  -workspace ./RNMapboxGLExample.xcworkspace -scheme RNMapboxGLExample | xcpretty -c
  fi
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    cd $TRAVIS_BUILD_DIR/example/android
    TERM=dumb ./gradlew assemble
  fi
- cd $TRAVIS_BUILD_DIR
- yarn global add -g 'jest@24.8.0'
- yarn install --ignore-engines
- yarn run unittest
- yarn run generate
deploy:
  provider: npm
  edge: true
  email: kristfallro@gmail.com
  api_key:
    secure: XP74gf8AAWkjMRBYzOQcSbU5uLSQA5Y7UYHjTPd+At/nBuf/38hkiZ/oOkJUNSVtc76zfCdnLRjXRFgGNYYH4XPe9vviaENWs0ykrT8H0OBhkKARF7w/R55uZF9IByOyOqnl2VviGgXHIJNCjZCr+r1Nm3nenfNdyEFfR6RT/5ZilsoZbvfZ/fs74HH3NE27q4T+mdgF9hgDOVO+p1tfGn0P7yGUbRhytQhMWkyeFnaYnu4kNv/aWWIkbzwEdOg1fYcjYv7LZVxaQFmrKpMDlyoBn9K3RwWgKX0mVR/IHfM0U3Vz0C/s9Zym8i9nBiJuBR0dH6tBwCgu/ORL+bX5PmuHYIk/vTcvU3dh0sFmdE8z6dFAThlHvNQMy9jW7QaYeBrnzDITyQMghI9+cBgnOtL0tlMU2TeAsbyfxjfr6HvOrKJiCQCv3kL7FoXCCtdlWjHnYHBzazj35bZYzyOEFFcyNe9Qe6pVwdz4AbAF1Tw0KmpZtfJTqNl512hmEFV9J2/0qIYvX7K+dlacRLKMImAwaU3pnkS40qXCAVnmSBHd3lq3QmIXp0t+QSuqRr88FOMAV/ShJDwbT2juCs13iLHHX4Jr1KCTowGatjoKbV/3OyuB9qpdsz62a7HAw3YulU1cnHRt8cTADb/7S0UZCy0TBzPKitg8MHSyQqEyvEs=
  on:
    tags: true
    repo: react-native-mapbox-gl/maps
    branch: master
    condition: $TRAVIS_OS_NAME = linux

